language: scala

scala:
- 2.13.4
- 2.12.13

services:
  - postgresql

before_install:
- curl -sf https://gobinaries.com/tj/mmake/cmd/mmake | sudo sh
- alias make=mmake

script:
- mmake test_ci

after_success:
- echo 'Done!'