up:
	cd NextCloud-docker-server && sudo docker-compose up -d

up_log:
	cd NextCloud-docker-server && sudo docker-compose up

down:
	cd NextCloud-docker-server && sudo docker-compose down

rebuild:
	cd NextCloud-docker-server && sudo docker-compose build --no-cache

stop-nc01:
	cd NextCloud-docker-server && sudo docker-compose stop nextcloud01

stop-nc02:
	cd NextCloud-docker-server && sudo docker-compose stop nextcloud02

stop-nc03:
	cd NextCloud-docker-server && sudo docker-compose stop nextcloud03

start-nc01:
	cd NextCloud-docker-server && sudo docker-compose start nextcloud01

start-nc02:
	cd NextCloud-docker-server && sudo docker-compose start nextcloud02

start-nc03:
	cd NextCloud-docker-server && sudo docker-compose start nextcloud03