version: '3'

networks:
  app-tier:

services:
    nginx:
      build: ./nginx
      ports:
        - '31010:80'
      networks: 
        - app-tier
      tty: true
      links:
      - nextcloud01
      - nextcloud02
      - nextcloud03
    nextcloud01:
      build:
        ./nextcloud
      restart: always
      volumes:
      - nextcloud:/var/www/html
      environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      depends_on: 
      - mariadb
      networks: 
      - app-tier
      links:
      - mariadb
    nextcloud02:
      build:
        ./nextcloud
      restart: always
      volumes:
      - nextcloud:/var/www/html
      environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      depends_on: 
      - mariadb
      networks: 
      - app-tier

    nextcloud03:
      build:
        ./nextcloud
      restart: always
      volumes:
      - nextcloud:/var/www/html
      environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      depends_on: 
      - mariadb
      networks: 
      - app-tier

    mariadb:
      image: "mariadb:10.4.8-bionic"
      command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
      restart: always
      volumes:
      - db:/var/lib/mysql
      networks: 
      - app-tier
      environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    openldap:
      image: osixia/openldap
      ports:
        - '389:389'
        - '636:636'
      restart: always
      environment:
        - LDAP_ADMIN_USERNAME=admin
        - LDAP_ADMIN_PASSWORD=adminpassword
        - LDAP_USERS=user01,user02
        - LDAP_PASSWORDS=password1,password2
      networks: 
      - app-tier
      volumes:
        - 'openldap_data:/bitnami/openldap'
volumes:
    openldap_data:
    nextcloud:      
    db:    