version: '3'

services:
  nginx:
     network_mode: host
     image: nginx:alpine
     ports:
        - 80:80
     # directorios para el archivo de configuración y archivos del static
     volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - ./backend/static/:/code/static
     depends_on:
        - web
  web:
    build: backend
    network_mode: host
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - ./datos_db:/data/db