(function(){/*

SPF
(c) 2012-2014 Google, Inc.
License: MIT
*/
function l(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(b,c)}}function aa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function m(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}function n(){return(new Date).getTime()};function ba(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function p(a,b){if(a.classList)return a.classList.contains(b);for(var c=ba(a),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0;return!1}function ca(a,b){a.classList?a.classList.add(b):p(a,b)||(a.className+=" "+b)}function da(a,b){if(a.classList)a.classList.remove(b);else{for(var c=ba(a),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ")}};function ea(a,b,c,d){var e=d||{},f=!1,g=0,h,k=new XMLHttpRequest;k.open(a,b,!0);k.timing={};var q=k.abort;k.abort=function(){clearTimeout(h);k.onreadystatechange=null;q.call(k)};k.onreadystatechange=function(){var a=k.timing;if(2==k.readyState){a.responseStart=a.responseStart||n();f=-1<(k.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked");if(!f){var a=k.getResponseHeader("X-Firefox-Spdy"),c=window.chrome&&chrome.loadTimes&&chrome.loadTimes(),c=c&&c.wasFetchedViaSpdy;f=!(!a&&
!c)}e.v&&e.v(k)}else 3==k.readyState?f&&e.l&&(a=k.responseText.substring(g),g=k.responseText.length,e.l(k,a)):4==k.readyState&&(a.responseEnd=a.responseEnd||n(),window.performance&&window.performance.getEntriesByName&&(k.resourceTiming=window.performance.getEntriesByName(b)[0]),f&&e.l&&k.responseText.length>g&&(a=k.responseText.substring(g),g=k.responseText.length,e.l(k,a)),clearTimeout(h),e.u&&e.u(k))};a="POST"==a;if(e.headers)for(var D in e.headers)k.setRequestHeader(D,e.headers[D]),"content-type"==
D.toLowerCase()&&(a=!1);a&&k.setRequestHeader("Content-Type","application/x-www-form-urlencoded");0<e.A&&(h=setTimeout(function(){k.abort();e.w&&e.w(k)},e.A));k.timing.fetchStart=n();k.send(c);return k};function r(a,b){return s[a]=b}var s=window._spf_state||{};window._spf_state=s;function t(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function u(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function fa(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;t(a,function(a,e,f){c[e]=b.call(void 0,a,e,f)});return c}function v(a){return"[object Array]"==Object.prototype.toString.call(a)?a:[a]};var ga={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"request-timeout":0,"url-identifier":"?spf=__type__"},w={};"config"in s||r("config",w);w=s.config;function ha(a,b){var c=b||document;return c.querySelectorAll?c.querySelectorAll(a):[]}function ia(a){var b,c=a.parentNode;if(c&&11!=c.nodeType)if(a.removeNode)a.removeNode(!1);else{for(;b=a.firstChild;)c.insertBefore(b,a);c.removeChild(a)}}function ja(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}
function ka(a,b,c){a=a||"";b=b||document;var d=b.createElement("iframe");d.id=a;d.src='javascript:""';d.style.display="none";c&&(d.onload=l(c,null,d));b.body.appendChild(d);return d};function la(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function ma(a){return"[object String]"==Object.prototype.toString.call(a)}var x=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function na(a){a=a.split("#");return[a[0],a.slice(1).join("#")]};function oa(a){var b=y();a in b&&delete b[a]}function pa(){var a=y(),b;for(b in a)qa(a[b])||delete a[b];a=y();b=parseInt(w["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(0>=b))for(var c=0;c<b;c++){var d=Infinity,e,f;for(f in a)a[f].count<d&&(e=f,d=a[f].count);delete a[e]}}function qa(a){if(!(a&&"data"in a))return!1;var b=a.life,b=isNaN(b)?Infinity:b;return n()-a.time<b}function ra(a){var b=parseInt(s["cache-counter"],10)||0;b++;r("cache-counter",b);a.count=b}
function y(){return"cache-storage"in s?s["cache-storage"]:r("cache-storage",{})};function sa(a,b,c,d){var e=window.history.state;d&&e&&(b=b||e);ta(!0,a,b,c)}function ta(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=n();r("history-timestamp",e);c["spf-timestamp"]=e;if(a)ua(c,b);else if(a=va().contentWindow.history.pushState,"function"==typeof a)a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");r("history-url",b);d&&(d=s["history-callback"])&&d(b,c)}}
function wa(a){var b=window.location.href;if(s["history-ignore-pop"])r("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==s["history-url"]?(r("history-timestamp",c),ua(a,b)):(a["spf-back"]=c<parseInt(s["history-timestamp"],10),a["spf-current"]=s["history-url"],r("history-timestamp",c),r("history-url",b),(c=s["history-callback"])&&c(b,a))}}
function ua(a,b){var c=va().contentWindow.history.replaceState;if("function"==typeof c)c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function va(){var a=document.getElementById("history-iframe");a||(a=ka("history-iframe"));return a};function xa(a,b){a&&b&&(a in z||(z[a]=[]),z[a].push(b))}function ya(a,b){a in z&&b&&u(z[a],function(a,d,e){return a==b?(e[d]=null,!1):!0})}function za(a){a in z&&t(z[a],function(a,c,d){d[c]=null;a&&a()})}var z={};"ps-s"in s||r("ps-s",z);z=s["ps-s"];function A(a,b,c){var d=B[a];return a&&b?(d||(d=B[a]={items:[],k:0,n:1}),d.items.push({F:b,D:c||0})):d&&d.items.length||0}function C(a,b){var c=B[a];if(c){var d=0<c.k;0<c.n&&(b||!d)&&Aa(a,b)}}function E(a){(a=B[a])&&a.n--}function F(a,b){var c=B[a];c&&(c.n++,C(a,b))}function Ba(a){var b=B[a];b&&(clearTimeout(b.k),delete B[a])}function Ca(a){var b=parseInt(s.uid,10)||0;b++;return a["spf-key"]||(a["spf-key"]=""+r("uid",b))}
function Aa(a,b){var c=B[a];if(c&&(clearTimeout(c.k),c.k=0,0<c.n)){var d=c.items.shift();if(d){var e=l(function(a,b){a();b()},null,d.F,l(Aa,null,a,b));b?e():c.k=setTimeout(e,d.D)}}}var B={};function G(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,H:b.H,G:b.G};a.origin=a.protocol+"//"+a.host;a.pathname&&"/"==a.pathname[0]||(a.pathname="/"+a.pathname);return a}function H(a){a=G(a);return na(a.href)[0]};function Da(a,b,c,d){var e="js"==a;b=v(b);var f=ma(c),g=f?c:"",h=f?d:c;b=fa(b,l(I,null,a));c=h;if(g){d=u(b,l(Ea,null,a));var k=J[a+"-"+g];!d&&k&&(m(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:g,urls:k}),delete J[a+"-"+g],c=function(){Fa(a,g,k);h&&h()})}e=g||"^"+b.sort().join("^");J[a+"-"+e]=b;xa(a+"-"+e,c);t(b,function(b){K[a+"-"+b]?Ga(a):(b=L(a,b,l(Ga,null,a)))&&g&&b.setAttribute("name",g)})}function Ha(a,b){var c=J[a+"-"+b]||[];delete J[a+"-"+b];Fa(a,b,c)}
function Fa(a,b,c){c.length&&(m("js"==a?"spfjsunload":"spfcssunload",{name:b,urls:c}),t(c,function(b){Ia(a,b)}))}function Ga(a){var b=a+"-",c;for(c in z)0==c.indexOf(b)&&u(c.substring(b.length).split("|"),l(Ja,null,a))&&za(c)}
function L(a,b,c,d){function e(){K[a+"-"+b]&&(K[a+"-"+b]=2);f&&h&&h.parentNode&&g==document&&h.parentNode.removeChild(h);c&&setTimeout(c,0);return null}var f="js"==a;b=I(a,b);K[a+"-"+b]=1;var g=d||document,h=g.createElement(f?"script":"link");if(!b)return e();d=M(b);h.className=a+"-"+d;"onload"in h?h.onerror=h.onload=e:h.onreadystatechange=function(){/^c|loade/.test(h.readyState)&&e()};d=g.getElementsByTagName("head")[0];f?(h.async=!0,h.src=b,d.insertBefore(h,d.firstChild)):(h.rel="stylesheet",h.href=
b,d.appendChild(h));return h}function Ia(a,b){b=I(a,b);var c=M(b),c=ha("."+(a+"-"+c),void 0);t(c,function(a){a&&a.parentNode&&a.parentNode.removeChild(a)});delete K[a+"-"+b]}function Ka(a){var b="js"==a,c=[];t(ha(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href,e=I(a,e);if(!K[a+"-"+e]){K[a+"-"+e]=2;var f=M(e);ca(d,a+"-"+f);(f=d.getAttribute("name"))&&(J[a+"-"+f]=[e]);c.push(d)}})}
function La(a,b){if(b&&(b=I(a,b),!K[a+"-"+b])){var c=M(b),d=a+"-"+c,e=a+"-prefetch",c=document.getElementById(e);if(!c)c=ka(e,null,function(a){a.title=e;C(e,!0)});else if(c.contentWindow.document.getElementById(d))return;d=l(Ma,null,c,a,b,d);c.title?d():A(e,d)}}function Ma(a,b,c,d){a=a.contentWindow.document;"js"==b?(b=a.createElement("object"),Na?a.createElement("script").src=c:b.data=c,b.id=d,a.body.appendChild(b)):(b=L(b,c,null,a),b.id=d)}
function Oa(a,b,c){for(var d="js"==a,e=J[a+"-"+c],f=b.replace(/\s/g,""),f=f||"",g=0,h=0,k=f.length;h<k;++h)g=31*g+f.charCodeAt(h),g%=4294967296;f="hash-"+g;J[a+"-"+c]=[f];!Ea(a,f)&&(b=N(a,b))&&(K[a+"-"+f]=2,b&&!d&&(d=M(f),b.className=a+"-"+d,b.setAttribute("name",c)),(e=e&&e[0])&&Ia(a,e))}
function N(a,b){b=x(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body,d;"js"==a?(d=document.createElement("script"),d.text=b,c.appendChild(d),c.removeChild(d)):(d=document.createElement("style"),c.appendChild(d),"styleSheet"in d?d.styleSheet.cssText=b:d.appendChild(document.createTextNode(b)));return d}
function I(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(0>d){if(0==b.lastIndexOf("hash-",0))return b;c=s[c]||"";if(ma(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);b=0>b.indexOf("."+a)?b+"."+a:b;b=H(b)}else 0==d&&(b=H(b))}return b}function Pa(a){return"js-"+a}function M(a){return a?String(a).replace(/[^\w]/g,""):""}function Ea(a,b){return 2==K[a+"-"+b]}function Ja(a,b){var c=J[a+"-"+b],d=l(Ea,null,a);return!b||!!c&&u(c,d)}var K={},J={},Na=-1!=navigator.userAgent.indexOf(" Trident/");
"rsrc-s"in s||r("rsrc-s",K);K=s["rsrc-s"];"rsrc-u"in s||r("rsrc-u",J);J=s["rsrc-u"];function O(a,b,c){Da("js",a,b,c)}function Qa(a){Ha("js",a)}function Ra(a,b){L("js",a,b)}function Sa(a){a=v(a);t(a,function(a){La("js",a)})}function Ta(a,b,c){a=v(a);var d=[];t(a,function(a){a&&!J["js-"+a]&&d.push(a)});var e=!d.length;if(b){var f=u(a,l(Ja,null,"js"));e&&f?b():(a=Pa(a.sort().join("|")),xa(a,b))}c&&!e&&c(d)}function Ua(a,b){a=v(a);t(a,function(a){a&&Va(a,P[a]||a)&&Wa(a)});Ta(a,b,Xa)}function Xa(a){t(a,function(a){function c(){O(e,a)}var d=Q[a],e=P[a]||a;d?Ua(d,c):c()})}
function Wa(a){a=v(a);t(a,function(a){var c=[],d;for(d in Q){var e=Q[d],e=v(e);t(e,function(e){e==a&&c.push(d)})}t(c,function(a){Wa(a)});Qa(a)})}function Ya(a,b){Oa("js",a,b)}function Za(a){N("js",a)}function Va(a,b){var c=J["js-"+a];return c?(b=v(b),!u(c,function(a,e){return c[e]==I("js",b[e])})):!1}var Q={};"js-d"in s||r("js-d",Q);var Q=s["js-d"],P={};"js-u"in s||r("js-u",P);P=s["js-u"];function $a(a,b,c){Da("css",a,b,c)}function ab(a,b){L("css",a,b)}function bb(a){a=v(a);t(a,function(a){La("css",a)})};function cb(a,b,c){if(b){var d=[],e;b=0;c&&(a+="\r\n");var f=a.indexOf("[\r\n",b);for(-1<f&&(b=f+3);-1<(f=a.indexOf(",\r\n",b));)e=x(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e));f=a.indexOf("]\r\n",b);-1<f&&(e=x(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e)));e="";a.length>b&&(e=a.substring(b),c&&la(e,"\r\n")&&(e=e.substring(0,e.length-2)));return{j:d,a:e}}a=JSON.parse(a);"number"==typeof a.length?d=a:d=[a];return{j:d,a:""}}
function R(a,b,c,d,e){var f="process "+H(a),g=!w["experimental-process-async"],h;h=0;b.timing||(b.timing={});b.title&&(document.title=b.title);d&&b.url&&H(b.url)!=H(window.location.href)&&sa(b.url+window.location.hash,null,!1,!0);b.head&&(h=l(function(a,b){var c=S(a);T(c);E(f);U(c,function(){b.spfProcessHead=n();F(f,g)})},null,b.head,b.timing),h=A(f,h));b.attr&&(h=l(function(a,b){for(var c in a){var d=document.getElementById(c);if(d){var e=a[c],f=void 0;for(f in e){var g=e[f];"class"==f?d.className=
g:"style"==f?d.style.cssText=g:d.setAttribute(f,g)}}}b.spfProcessAttr=n()},null,b.attr,b.timing),h=A(f,h));d=b.body||{};var k=h,q;for(q in d)h=l(function(a,b){var c=document.getElementById(a);if(c){var d=S(b),h=w["animation-class"];if(db&&p(c,h)){E(f);var k=Ca(c);C(k,!0);h={p:d,reverse:!!e,f:null,h:null,g:c,B:h+"-old",C:h+"-new",t:e?h+"-reverse-start":h+"-forward-start",s:e?h+"-reverse-end":h+"-forward-end"};c=l(function(a){T(a.p);ca(a.g,a.t);a.f=document.createElement("div");a.f.className=a.B;var b=
a.g,c=a.f;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.h=document.createElement("div");a.h.className=a.C;a.h.innerHTML=a.p.i;a.reverse?(b=a.f,b.parentNode.insertBefore(a.h,b)):(b=a.f,b.parentNode.insertBefore(a.h,b.nextSibling))},null,h);A(k,c,0);c=l(function(a){da(a.g,a.t);ca(a.g,a.s)},null,h);A(k,c,0);c=l(function(a){a.g.removeChild(a.f);da(a.g,a.s);ia(a.h);E(k);U(a.p,function(){F(k)})},null,h);A(k,c,parseInt(w["animation-duration"],10));c=l(function(a,b){F(b)},null,h,f);
A(k,c);C(k)}else{T(d);var q=function(){E(f);U(d,function(){F(f,g)})};(h=w["experimental-html-handler"])?(E(f),h(d.i,c,function(){q();F(f,g)})):(c.innerHTML=d.i,q())}}},null,q,d[q],b.timing),h=A(f,h);q=h-k;b.foot?(h=l(function(a,b,c){c&&(b.spfProcessBody=n());a=S(a);T(a);E(f);U(a,function(){b.spfProcessFoot=n();F(f,g)})},null,b.foot,b.timing,q),h=A(f,h)):q&&(h=l(function(a){a.spfProcessBody=n()},null,b.timing),h=A(f,h));c&&(h=A(f,l(c,null,a,b)));C(f,g)}
function eb(a,b,c){var d="preprocess "+H(a),e;b.head&&(e=l(function(a){a=S(a);fb(a);gb(a)},null,b.head),A(d,e));var f=b.body||{},g;for(g in f)f[g]&&(e=l(function(a,b){var c=S(b);fb(c);gb(c)},null,g,f[g]),A(d,e));b.foot&&(e=l(function(a){a=S(a);fb(a);gb(a)},null,b.foot),A(d,e));c&&A(d,l(c,null,a,b));C(d)}
function S(a){var b=new hb;if(!a)return b;if(!ma(a))return a.scripts&&t(a.scripts,function(a){b.d.push({url:a.url||"",text:a.text||"",name:a.name||"",async:a.async||!1})}),a.styles&&t(a.styles,function(a){b.c.push({url:a.url||"",text:a.text||"",name:a.name||""})}),b.i=a.html||"",b;a=a.replace(ib,function(a,d,e,f){return"script"==d?(a=(a=e.match(jb))?a[1]:"",d=(d=e.match(kb))?d[1]:"",e=lb.test(e),b.d.push({url:d,text:f,name:a,async:e}),""):"style"==d?(a=(a=e.match(jb))?a[1]:"",b.c.push({url:"",text:f,
name:a}),""):a});a=a.replace(mb,function(a,d){var e=d.match(nb),e=e?e[1]:"";if("stylesheet"==e){var e=(e=d.match(jb))?e[1]:"",f=d.match(ob),f=f?f[1]:"";b.c.push({url:f,text:"",name:e});return""}return a});b.i=a;return b}
function U(a,b){if(0>=a.d.length)b&&b();else{var c=-1,d=function(){c++;if(c<a.d.length){var e=a.d[c],f=function(){};e.url?f=w["experimental-execute-unified"]?e.name?l(O,null,e.url,e.name):l(Ra,null,e.url):l(O,null,e.url,e.name):e.text&&(f=w["experimental-execute-unified"]?e.name?l(Ya,null,e.text,e.name):l(Za,null,e.text):l(Za,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}function gb(a){0>=a.d.length||(a=fa(a.d,function(a){return a.url}),Sa(a))}
function T(a){if(!(0>=a.c.length))for(var b=0,c=a.c.length;b<c;b++){var d=a.c[b];d.url?w["experimental-execute-unified"]?d.name?$a(d.url,d.name):ab(d.url):$a(d.url,d.name):d.text&&(w["experimental-execute-unified"]?d.name?Oa("css",d.text,d.name):N("css",d.text):N("css",d.text))}}function fb(a){0>=a.c.length||(a=fa(a.c,function(a){return a.url}),bb(a))}function hb(){this.i="";this.d=[];this.c=[]}
var db=function(){var a=document.createElement("div");if("transition"in a.style)return!0;for(var b=["webkit","Moz","Ms","O","Khtml"],c=0,d=b.length;c<d;c++)if(b[c]+"Transition"in a.style)return!0;return!1}(),mb=/\x3clink([\s\S]*?)\x3e/ig,ib=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,lb=/(?:\s|^)async(?:\s|=|$)/i,ob=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,jb=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,nb=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,kb=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i;function pb(a,b){var c=b||{};c.method=((c.method||"GET")+"").toUpperCase();c.type=c.type||"request";var d=a,e=w["url-identifier"]||"";if(e){var f=c.type||"",g="";-1!=d.indexOf("#")&&(g=na(d),d=g[0],g="#"+g[1]);e=e.replace("__type__",f);d=0==e.lastIndexOf("?",0)&&-1!=d.indexOf("?")?d+e.replace("?","&"):d+e;d+=g}d=H(d);e={};e.spfUrl=d;e.startTime=n();e.fetchStart=e.startTime;n:{var g=qb(a,c.current,null,c.type,!1),h=c.current,f=[];h&&(f.push(g+" previous "+h),f.push(g+" previous "+G(h).pathname));f.push(g);
g=0;for(h=f.length;g<h;g++){var k;r:{k=f[g];var q=y();if(k in q){q=q[k];if(qa(q)){ra(q);k=q.data;break r}oa(k)}k=void 0}if(k){f={key:f[g],response:k.response,type:k.type};break n}}f=null}e.spfPrefetched=!!f&&"prefetch"==f.type;e.spfCached=!!f;if(f)return setTimeout(l(rb,null,a,c,e,f.key,f.response),0),null;f={};void 0!=c.r&&(f["X-SPF-Referer"]=c.r);c.current&&(f["X-SPF-Previous"]=c.current);g={q:!1,a:"",complete:[]};e=l(sb,null,a,c,e,g);e={headers:f,A:w["request-timeout"],v:l(tb,null,a,g),l:l(ub,
null,a,c,g),u:e,w:e};return"POST"==c.method?ea("POST",d,c.o,e):ea("GET",d,null,e)}function rb(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=n();b.type&&0==b.type.lastIndexOf("navigate",0)&&(c.navigationStart=c.startTime,w["cache-unified"]||(oa(d),f=!0));if(b.b&&"multipart"==e.type){d=e.parts;for(var g=0;g<d.length;g++)b.b(a,d[g])}vb(a,b,c,e,f)}function tb(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.q=-1!=a.toLowerCase().indexOf("multipart")}
function ub(a,b,c,d,e,f){if(c.q){e=c.a+e;var g;try{g=cb(e,!0,f)}catch(h){d.abort();b.e&&b.e(a,h);return}if(b.b)for(d=0;d<g.j.length;d++)b.b(a,g.j[d]);c.complete=c.complete.concat(g.j);c.a=g.a}}
function sb(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if("load"==b.type)for(var g in e.resourceTiming)c[g]=e.resourceTiming[g];else if(window.performance&&window.performance.timing){f=window.performance.timing.navigationStart;for(var h in e.resourceTiming)g=e.resourceTiming[h],void 0!==g&&(la(h,"Start")||la(h,"End")||"startTime"==h)&&(c[h]=f+Math.round(g))}"load"!=b.type&&(c.navigationStart=c.startTime);d.complete.length&&(d.a=x(d.a),d.a&&ub(a,b,d,e,"",!0));
var k;try{k=cb(e.responseText).j}catch(q){b.e&&b.e(a,q);return}if(b.b&&1<k.length)for(d=d.complete.length;d<k.length;d++)b.b(a,k[d]);if(1<k.length){var D;d=0;for(e=k.length;d<e;d++)h=k[d],h.cacheType&&(D=h.cacheType);k={parts:k,type:"multipart"};D&&(k.cacheType=D)}else k=1==k.length?k[0]:{};vb(a,b,c,k,!0)}
function vb(a,b,c,d,e){if(e&&"POST"!=b.method&&(e=qb(a,b.current,d.cacheType,b.type,!0))){var f={response:d,type:b.type||""},g=parseInt(w["cache-lifetime"],10),h=parseInt(w["cache-max"],10);0>=g||0>=h||(h=y(),f={data:f,life:g,time:n(),count:0},ra(f),h[e]=f,setTimeout(pa,1E3))}d.timing=c;b.m&&b.m(a,d)}
function qb(a,b,c,d,e){a=H(a);var f;w["cache-unified"]?f=a:"navigate-back"==d||"navigate-forward"==d?f="history "+a:"navigate"==d?f=(e?"history ":"prefetch ")+a:"prefetch"==d&&(f=e?"prefetch "+a:"");b&&"url"==c?f+=" previous "+b:b&&"path"==c&&(f+=" previous "+G(b).pathname);return f||""};function wb(a){return ja(a,function(a){return p(a,w["link-class"])})}function xb(a){return ja(a,function(a){return p(a,w["nolink-class"])})}function yb(a,b){return ja(a,function(a){return a.href&&"img"!=a.tagName.toLowerCase()},b)}function zb(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||0<a.button)return null;var b=wb(a.target);return!b||w["nolink-class"]&&xb(a.target)?null:(a=yb(a.target,b))?a.href:null}function Ab(a){return G(a).origin!=G(window.location.href).origin?!1:!0}
function Bb(){if(!s["nav-init"])return!1;var a=parseInt(s["nav-counter"],10)||0;a++;var b=parseInt(w["navigate-limit"],10),b=isNaN(b)?Infinity:b;if(a>b)return!1;a=parseInt(s["nav-time"],10);a--;a=n()-a;b=parseInt(w["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}
function Cb(a){if(!a.defaultPrevented){var b=zb(a);null!==b&&(b&&b!=window.location.href?(!w["experimental-same-origin"]||Ab(b))&&Bb()&&m("spfclick",{url:b,target:a.target})&&(Db(b),a.preventDefault()):a.preventDefault())}}function Eb(a){var b=zb(a);b&&b!=window.location.href&&setTimeout(function(){Fb(b,void 0)},0)}
function Gb(a,b){var c=!(!b||!b["spf-back"]),d=b&&b["spf-referer"],e=b&&b["spf-current"];w["experimental-same-origin"]&&!Ab(a)?V(a,"9"):Bb()?m("spfhistory",{url:a,referer:d,previous:e})&&Db(a,null,e,d,!0,c):V(a,"1")}
function Db(a,b,c,d,e,f){b=b||{};r("nav-counter",(parseInt(s["nav-counter"],10)||0)+1);r("nav-time",n());d=void 0==d?window.location.href:d;r("nav-referer",d);c=e?c:window.location.href;if(Hb(a,d,c,b)){W();Ib(a);var g=H(a),h="preprocess "+H(g),k;for(k in B)h!=k&&0==k.lastIndexOf("preprocess",0)&&Ba(k);k=Jb()[g];r("nav-request",k);r("nav-promote",null);r("nav-promote-time",null);k&&4!=k.readyState?(f=!!e,e="preprocess "+H(a),c="promote "+H(a),r("nav-promote",a),r("nav-promote-time",n()),Ba(e),C(c,
!0),f||Kb(a,d,l(X,null,b))):(e=!!e,k=!!f,f=l(X,null,b),b=pb(a,{method:b.method,b:l(Lb,null,b,k),e:f,m:l(Mb,null,b,k,""),o:b.postData,type:"navigate"+(e?k?"-back":"-forward":""),current:c,r:d}),r("nav-request",b),e||Kb(a,d,f))}else V(a,"2")}function Kb(a,b,c){try{ta(!1,a,{"spf-referer":b},void 0)}catch(d){W(),c(a,d)}}function X(a,b,c){r("nav-request",null);Nb(b,c,a)&&(a="10",c&&(a+=" Message: "+c.message),V(b,a))}
function Lb(a,b,c,d){if(Ob(c,d,a))if(d.redirect)Pb(a,d.redirect);else try{R(c,d,function(){Qb(c,d,a)},!0,b)}catch(e){X(a,c,e)}else V(c,"3")}function Mb(a,b,c,d,e){r("nav-request",null);s["nav-promote"]==c&&(c=e.timing||{},c.navigationStart=s["nav-promote-time"],c.spfPrefetched=!0);c="multipart"==e.type;if(!c){if(!Rb(d,e,a)){V(d,"4");return}if(e.redirect){Pb(a,e.redirect);return}}try{R(d,c?{}:e,function(){Sb(d,e,a)},!0,b)}catch(f){X(a,d,f)}}
function Pb(a,b){try{b+=window.location.hash,sa(b,null,!0,!0)}catch(c){W(),X(a,b,c)}}function W(){var a=s["nav-request"];a&&(a.abort(),r("nav-request",null))}function Y(a,b){var c;a&&(c=Array.prototype.slice.call(arguments),c[0]=a,c=aa.apply(null,c));return!1!==c}function V(a,b){W();Ib();m("spfreload",{url:a,reason:b});w["experimental-remove-history"]&&window.location.href==a&&(r("history-ignore-pop",!0),window.history.back());setTimeout(function(){window.location.href=a},0)}
function Tb(a,b,c){b=b||{};c=c||a;Hb(a,void 0,void 0,b,!0)&&pb(a,{method:b.method,b:l(Ub,null,!1,b,c),e:l(Vb,null,!1,b,c),m:l(Wb,null,!1,b,c),o:b.postData,type:"load"})}function Fb(a,b,c){b=b||{};c=c||a;var d=window.location.href;Hb(a,void 0,void 0,b,!0)&&(b=pb(a,{method:b.method,b:l(Ub,null,!0,b,c),e:l(Vb,null,!0,b,c),m:l(Wb,null,!0,b,c),o:b.postData,type:"prefetch",current:d}),a=H(a),Jb()[a]=b)}function Vb(a,b,c,d,e){a&&Xb(d);a&&s["nav-promote"]==c?X(b,d,e):Nb(d,e,b,!0)}
function Ub(a,b,c,d,e){if(Ob(d,e,b,!0))if(e.redirect)Yb(a,b,c,e.redirect);else{if(a){var f=l(Lb,null,b,!1,d,e),g="promote "+H(c);A(g,f);if(s["nav-promote"]==c){C(g,!0);return}}(a?eb:R)(d,e,function(){Qb(d,e,b,!0)})}}
function Wb(a,b,c,d,e){var f="multipart"==e.type;if(!f){if(!Rb(d,e,b,!0)){V(d,"4");return}if(e.redirect){Yb(a,b,c,e.redirect);return}}var g="promote "+H(c);if(a){Xb(d);if(s["nav-promote"]==c){A(g,l(Mb,null,b,!1,c,d,e));C(g,!0);return}Ba(g)}g=a?eb:R;try{g(d,f?{}:e,function(){Sb(d,e,b,!0)})}catch(h){Vb(a,b,c,d,h)}}function Yb(a,b,c,d){a=a?Fb:Tb;var e={};t("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(a){e[a]=b[a]});a(d,e,c)}
function Nb(a,b,c,d){a={url:a,err:b};(c=Y((c||{}).onError,a))&&!d&&(c=m("spferror",a));return c}function Hb(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=Y((d||{}).onRequest,a))&&!e&&(d=m("spfrequest",a));return d}function Ob(a,b,c,d){a={url:a,part:b};(c=Y((c||{}).onPartProcess,a))&&!d&&(c=m("spfpartprocess",a));return c}function Qb(a,b,c,d){a={url:a,part:b};Y((c||{}).onPartDone,a)&&!d&&m("spfpartdone",a)}
function Rb(a,b,c,d){a={url:a,response:b};(c=Y((c||{}).onProcess,a))&&!d&&(c=m("spfprocess",a));return c}function Sb(a,b,c,d){a={url:a,response:b};Y((c||{}).onDone,a)&&!d&&m("spfdone",a)}function Xb(a){a=H(a);var b=Jb(),c=b[a];c&&c.abort();delete b[a]}function Ib(a){var b=Jb();a=a&&H(a);for(var c in b)a!=c&&Xb(c)}function Jb(){return"nav-prefetches"in s?s["nav-prefetches"]:r("nav-prefetches",{})};function Z(){Ka("js");Ka("css");"complete"==document.readyState&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",Z,!1):document.detachEvent&&document.detachEvent("onreadystatechange",Z))}document.addEventListener?document.addEventListener("DOMContentLoaded",Z,!1):document.attachEvent&&document.attachEvent("onreadystatechange",Z);Z();
var Zb={init:function(a){var b=!("function"!=typeof window.history.pushState&&!va().contentWindow.history.pushState);a=a||{};for(var c in ga)w[c]=c in a?a[c]:ga[c];for(c in a)c in ga||(w[c]=a[c]);if(b){c=Nb;if(!s["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",wa,!1);r("history-init",!0);r("history-callback",Gb);r("history-error-callback",c);r("history-listener",wa);r("history-url",a);r("history-timestamp",n());var d={"spf-referer":document.referrer};
try{sa(a,d)}catch(e){c&&c(a,e)}}!s["nav-init"]&&document.addEventListener&&(document.addEventListener("click",Cb,!1),!w["experimental-prefetch-mousedown"]||"ontouchstart"in window||0<window.navigator.maxTouchPoints||0<window.navigator.msMaxTouchPoints||(document.addEventListener("mousedown",Eb,!1),r("prefetch-listener",Eb)),r("nav-init",!0),r("nav-counter",0),r("nav-time",n()),r("nav-listener",Cb))}return b},dispose:function(){"undefined"!=typeof History&&History.prototype.pushState&&(W(),s["nav-init"]&&
(document.removeEventListener&&(document.removeEventListener("click",s["nav-listener"],!1),w["experimental-prefetch-mousedown"]&&document.removeEventListener("mousedown",s["prefetch-listener"],!1)),r("nav-init",!1),r("nav-counter",null),r("nav-time",null),r("nav-listener",null)),s["history-init"]&&(window.removeEventListener&&window.removeEventListener("popstate",s["history-listener"],!1),r("history-init",!1),r("history-callback",null),r("history-error-callback",null),r("history-listener",null),r("history-url",
null),r("history-timestamp",0)));for(var a in w)delete w[a]},navigate:function(a,b){a&&a!=window.location.href&&(w["experimental-same-origin"]&&!Ab(a)?V(a,"9"):Bb()?Db(a,b):V(a,"1"))},load:function(a,b){Tb(a,b)},process:R,prefetch:function(a,b){Fb(a,b)}},$b={script:{load:O,get:Ra,ready:Ta,done:function(a){J["js-"+a]=[];Ga("js")},require:Ua,declare:function(a,b){if(a){for(var c in a)Q[c]=a[c];if(b)for(c in b)P[c]=b[c]}},path:function(a){r("rsrc-p-js",a)},unload:Qa,ignore:function(a,b){a=v(a);var c=
Pa(a.sort().join("|"));ya(c,b)},unrequire:Wa,prefetch:Sa},style:{load:$a,get:ab,unload:function(a){Ha("css",a)},path:function(a){r("rsrc-p-css",a)},prefetch:bb}},ac=this.spf=this.spf||{},bc;for(bc in Zb)ac[bc]=Zb[bc];for(var $ in $b)for(var cc in $b[$])ac[$]=ac[$]||{},ac[$][cc]=$b[$][cc];m("spfready");})();
