version: 2
jobs:
  build:
    docker:
      - image: alvarodelaflor/coronaalert
        auth:
          username: $USERNAME
          password: $PASSWORD

      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: $USERNAME
          password: $PASSWORD
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13      
      - run: |
          sh -c "ls && make test_ci"